[package]
name = "print-nanny-cli"
version = "0.1.0"
authors = ["Leigh Johnson <hi@leighjohnson.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
