[package]
name = "printnanny"
version = "0.1.0"
authors = ["Leigh Johnson <leigh@bitsy.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_cmd = "1.0.7"
predicates = "2.0.0"

[dependencies]
anyhow = "1.0.42"
clap-verbosity-flag = "0.3.1"
env_logger = "0.8.4"
log = "0.4.14"
structopt = "0.3.22"